name: Deploy Specific Folder to Vercel

on:
  push:
    paths:
      - "techbite/**"  # Only trigger when files in 'techbite' change
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment for Project One
        run: curl -X POST "$VERCEL_HOOK"
        env:
          VERCEL_HOOK: ${{ secrets.VERCEL_HOOK }}
